// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FunkyTasks")]
[assembly: AssemblyProductAttribute("FunkyTasks")]
[assembly: AssemblyDescriptionAttribute("Functional combinators for System.Threading.Tasks")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
